//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UsersManagementEntities : DbContext
    {
        public UsersManagementEntities()
            : base("name=UsersManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<authorize_department> authorize_department { get; set; }
        public virtual DbSet<concept> concept { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<questions> questions { get; set; }
        public virtual DbSet<requests> requests { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
